print("..........................................")
print("Tugas 1 SISOP Kelas-B")
print("..........................................")
print("Nama : Alvin Ryan Dana")
print("NPM : 21083010035")
print("..........................................")
print("notes:")
print("..........................................")
print("Halo Dunia!")
print("Ini adalah skrip Bash pertamaku di linux")
print("..........................................")
